  development:
    adapter: postgresql
    database: descomplicando_dev
    username: postgres
    password: postgres
    host: 127.0.0.1
    encoding: utf8

  test:
    adapter: postgresql
    database: descomplicando_test
    username: postgres
    password: postgres
    host: 127.0.0.1
    encoding: utf8

  production:
    adapter: postgresql
    database: descomplicando
    username: postgres
    password: postgres
    host: 127.0.0.1
    encoding: utf8
